packages:
  all:
    require:
    - any_of: ['%intel-oneapi-compilers@=2025.3.0']
      when: '%intel-oneapi-compilers'
    - any_of: ['%gcc@=13.3.0']
      when: '%gcc'
  mpi:
    buildable: false
    require:
    - "intel-oneapi-mpi@=2021.17"
  intel-oneapi-compilers:
    buildable: false
    externals:
    - spec: intel-oneapi-compilers@=2025.3.0 +fix_rt_linkage
      prefix: /ford1/share/gmao_SIteam/intel/oneapi/2025
      extra_attributes:
        compilers:
          c: /ford1/share/gmao_SIteam/intel/oneapi/2025/compiler/2025.3/bin/icx
          cxx: /ford1/share/gmao_SIteam/intel/oneapi/2025/compiler/2025.3/bin/icpx
          fortran: /ford1/share/gmao_SIteam/intel/oneapi/2025/compiler/2025.3/bin/ifx
        extra_rpaths:
        - /ford1/share/gmao_SIteam/gcc/gcc-13.3.0/lib64
  gcc:
    buildable: false
    externals:
    - spec: gcc@=13.3.0 languages:='c,c++'
      prefix: /ford1/share/gmao_SIteam/gcc/gcc-13.3.0
      extra_attributes:
        compilers:
          c: /ford1/share/gmao_SIteam/gcc/gcc-13.3.0/bin/gcc
          cxx: /ford1/share/gmao_SIteam/gcc/gcc-13.3.0/bin/g++
  intel-oneapi-mpi:
    buildable: false
    externals:
    - spec: intel-oneapi-mpi@=2021.17
      prefix: /ford1/share/gmao_SIteam/intel/oneapi/2025/mpi/2021.17
